theme: jekyll-theme-cayman
site:
  title: CVKAVACH
  description: COVID19 Live Tracker
  show_downloads: true
  owner: Aditya Kumar
  app:
    url: https://play.google.com/store/apps/details?id=com.app.cvkavach
