name: Flutter Build and Publish Snapshots - Dev 

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-pacakge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: echo "Running tests"
  build_deploy:
    runs-on: ubuntu-latest
    name: Build apk
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - run: flutter upgrade
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - name: Build
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
          --output $HOME/secrets/secrets.tar secrets.tar.gpg
          tar xvf $HOME/secrets/secrets.tar
          flutter build appbundle
          flutter build apk
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - name: Create a Snapshot apk
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/bundle/release
