name: Flutter Build and Release - Prod

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test-pacakge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: echo "Running tests"
  build_deploy:
    runs-on: ubuntu-latest
    name: Build apk
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - uses: flutter upgrade
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run : flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Snapshot apk
        uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/bundle/release/app-release.apk